// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP_Clock

#ifndef _ESP_CLOCK_UI_H
#define _ESP_CLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_WiFiScreen.h"
#include "screens/ui_HomeScreen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_713335961);    // assets/Pokemon-Environment-Background_1_320x240.png
LV_IMG_DECLARE(ui_img_clock_nohands_png);    // assets/Clock_NoHands.png
LV_IMG_DECLARE(ui_img_clock_secondshand_s_png);    // assets/Clock_SecondsHand_s.png
LV_IMG_DECLARE(ui_img_hourhandre_png);    // assets/HourHandRe.png
LV_IMG_DECLARE(ui_img_mm_20_png);    // assets/mm_20.png
LV_IMG_DECLARE(ui_img_weather_png);    // assets/weather.png
LV_IMG_DECLARE(ui_img_weather_sun_png);    // assets/weather_sun.png
LV_IMG_DECLARE(ui_img_weather_cloud_png);    // assets/weather_cloud.png
LV_IMG_DECLARE(ui_img_piplup_png);    // assets/Piplup.png
LV_IMG_DECLARE(ui_img_mudkip_png);    // assets/Mudkip.png
LV_IMG_DECLARE(ui_img_wingull_png);    // assets/Wingull.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
