// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP_Clock

#ifndef UI_HOMESCREEN_H
#define UI_HOMESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HomeScreen
extern void ui_HomeScreen_screen_init(void);
extern void ui_HomeScreen_screen_destroy(void);
extern lv_obj_t * ui_HomeScreen;
extern lv_obj_t * ui_Clock;
extern lv_obj_t * ui_SecondHand;
extern lv_obj_t * ui_HourHand;
extern lv_obj_t * ui_MinuteHand;
extern lv_obj_t * ui_WeatherContainer;
extern lv_obj_t * ui_WeatherWidget;
extern lv_obj_t * ui_Temperature;
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_WeatherConditionContainer;
extern lv_obj_t * ui_PrecipitationText;
extern lv_obj_t * ui_HumidityText;
extern lv_obj_t * ui_WindText;
extern lv_obj_t * ui_AirQualityText;
extern lv_obj_t * ui_Percent1;
extern lv_obj_t * ui_Percent2;
extern lv_obj_t * ui_mph;
extern lv_obj_t * ui_WeatherConditionValContainer;
extern lv_obj_t * ui_PrecipitationValue;
extern lv_obj_t * ui_HumidityValue;
extern lv_obj_t * ui_WindValue;
extern lv_obj_t * ui_AirQualityValue;
extern lv_obj_t * ui_Celsius;
extern lv_obj_t * ui_DateTimeContainer;
extern lv_obj_t * ui_WeekContainer;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_DateContainer;
extern lv_obj_t * ui_Month;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Year;
extern lv_obj_t * ui_PlaceContainer;
extern lv_obj_t * ui_Location;
extern lv_obj_t * ui_MiscContainer;
extern lv_obj_t * ui_PokeContainer;
extern lv_obj_t * ui_Piplup;
extern lv_obj_t * ui_Mudkip;
extern lv_obj_t * ui_Ground;
extern lv_obj_t * ui_Wingull;
extern lv_obj_t * ui_ExtraContainer;
extern lv_obj_t * ui_ExtraLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

