// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP_Clock

#include "../ui.h"

lv_obj_t * ui_HomeScreen = NULL;
lv_obj_t * ui_Clock = NULL;
lv_obj_t * ui_SecondHand = NULL;
lv_obj_t * ui_HourHand = NULL;
lv_obj_t * ui_MinuteHand = NULL;
lv_obj_t * ui_WeatherContainer = NULL;
lv_obj_t * ui_WeatherWidget = NULL;
lv_obj_t * ui_Temperature = NULL;
lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_WeatherConditionContainer = NULL;
lv_obj_t * ui_PrecipitationText = NULL;
lv_obj_t * ui_HumidityText = NULL;
lv_obj_t * ui_WindText = NULL;
lv_obj_t * ui_AirQualityText = NULL;
lv_obj_t * ui_Percent1 = NULL;
lv_obj_t * ui_Percent2 = NULL;
lv_obj_t * ui_mph = NULL;
lv_obj_t * ui_WeatherConditionValContainer = NULL;
lv_obj_t * ui_PrecipitationValue = NULL;
lv_obj_t * ui_HumidityValue = NULL;
lv_obj_t * ui_WindValue = NULL;
lv_obj_t * ui_AirQualityValue = NULL;
lv_obj_t * ui_Celsius = NULL;
lv_obj_t * ui_DateTimeContainer = NULL;
lv_obj_t * ui_WeekContainer = NULL;
lv_obj_t * ui_Day = NULL;
lv_obj_t * ui_DateContainer = NULL;
lv_obj_t * ui_Month = NULL;
lv_obj_t * ui_Date = NULL;
lv_obj_t * ui_Year = NULL;
lv_obj_t * ui_PlaceContainer = NULL;
lv_obj_t * ui_Location = NULL;
lv_obj_t * ui_MiscContainer = NULL;
lv_obj_t * ui_PokeContainer = NULL;
lv_obj_t * ui_Piplup = NULL;
lv_obj_t * ui_Mudkip = NULL;
lv_obj_t * ui_Ground = NULL;
lv_obj_t * ui_Wingull = NULL;
lv_obj_t * ui_ExtraContainer = NULL;
lv_obj_t * ui_ExtraLabel = NULL;
// event funtions

// build funtions

void ui_HomeScreen_screen_init(void)
{
    ui_HomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_HomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HomeScreen, lv_color_hex(0x8ECAE6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_HomeScreen, lv_color_hex(0x219EBC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_HomeScreen, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_HomeScreen, lv_color_hex(0x003566), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_HomeScreen, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_HomeScreen, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_HomeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Clock = lv_img_create(ui_HomeScreen);
    lv_img_set_src(ui_Clock, &ui_img_clock_nohands_png);
    lv_obj_set_width(ui_Clock, LV_SIZE_CONTENT);   /// 145
    lv_obj_set_height(ui_Clock, LV_SIZE_CONTENT);    /// 150
    lv_obj_set_x(ui_Clock, 82);
    lv_obj_set_y(ui_Clock, -41);
    lv_obj_set_align(ui_Clock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Clock, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Clock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SecondHand = lv_img_create(ui_Clock);
    lv_img_set_src(ui_SecondHand, &ui_img_clock_secondshand_s_png);
    lv_obj_set_width(ui_SecondHand, LV_SIZE_CONTENT);   /// 4
    lv_obj_set_height(ui_SecondHand, LV_SIZE_CONTENT);    /// 65
    lv_obj_set_x(ui_SecondHand, -2);
    lv_obj_set_y(ui_SecondHand, 21);
    lv_obj_set_align(ui_SecondHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SecondHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_SecondHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_SecondHand, 2, 8);

    ui_HourHand = lv_img_create(ui_Clock);
    lv_img_set_src(ui_HourHand, &ui_img_hourhandre_png);
    lv_obj_set_width(ui_HourHand, LV_SIZE_CONTENT);   /// 8
    lv_obj_set_height(ui_HourHand, LV_SIZE_CONTENT);    /// 37
    lv_obj_set_x(ui_HourHand, -2);
    lv_obj_set_y(ui_HourHand, -20);
    lv_obj_set_align(ui_HourHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HourHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HourHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_HourHand, 4, 35);

    ui_MinuteHand = lv_img_create(ui_Clock);
    lv_img_set_src(ui_MinuteHand, &ui_img_mm_20_png);
    lv_obj_set_width(ui_MinuteHand, LV_SIZE_CONTENT);   /// 11
    lv_obj_set_height(ui_MinuteHand, LV_SIZE_CONTENT);    /// 59
    lv_obj_set_x(ui_MinuteHand, -2);
    lv_obj_set_y(ui_MinuteHand, -24);
    lv_obj_set_align(ui_MinuteHand, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MinuteHand, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_MinuteHand, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_pivot(ui_MinuteHand, 5, 50);

    ui_WeatherContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_WeatherContainer);
    lv_obj_set_width(ui_WeatherContainer, 145);
    lv_obj_set_height(ui_WeatherContainer, 117);
    lv_obj_set_x(ui_WeatherContainer, -73);
    lv_obj_set_y(ui_WeatherContainer, -54);
    lv_obj_set_align(ui_WeatherContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeatherContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherContainer, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WeatherContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WeatherContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_WeatherContainer, lv_color_hex(0xFAF5F5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_WeatherContainer, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WeatherContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherWidget = lv_img_create(ui_WeatherContainer);
    lv_img_set_src(ui_WeatherWidget, &ui_img_weather_png);
    lv_obj_set_width(ui_WeatherWidget, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherWidget, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherWidget, -30);
    lv_obj_set_y(ui_WeatherWidget, -34);
    lv_obj_set_align(ui_WeatherWidget, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherWidget, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_WeatherWidget, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_WeatherWidget, 400);

    ui_Temperature = lv_label_create(ui_WeatherContainer);
    lv_obj_set_width(ui_Temperature, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature, 6);
    lv_obj_set_y(ui_Temperature, -42);
    lv_obj_set_align(ui_Temperature, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Temperature, "18");
    lv_obj_set_style_text_font(ui_Temperature, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Weather = lv_label_create(ui_WeatherContainer);
    lv_obj_set_width(ui_Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Weather, 24);
    lv_obj_set_y(ui_Weather, -23);
    lv_obj_set_align(ui_Weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Weather, "Sunny");

    ui_WeatherConditionContainer = lv_obj_create(ui_WeatherContainer);
    lv_obj_remove_style_all(ui_WeatherConditionContainer);
    lv_obj_set_width(ui_WeatherConditionContainer, 75);
    lv_obj_set_height(ui_WeatherConditionContainer, 69);
    lv_obj_set_x(ui_WeatherConditionContainer, -18);
    lv_obj_set_y(ui_WeatherConditionContainer, 22);
    lv_obj_set_align(ui_WeatherConditionContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherConditionContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherConditionContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WeatherConditionContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrecipitationText = lv_label_create(ui_WeatherConditionContainer);
    lv_obj_set_width(ui_PrecipitationText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrecipitationText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrecipitationText, -13);
    lv_obj_set_y(ui_PrecipitationText, -7);
    lv_obj_set_align(ui_PrecipitationText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrecipitationText, "Precipitation •");
    lv_obj_set_style_text_font(ui_PrecipitationText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityText = lv_label_create(ui_WeatherConditionContainer);
    lv_obj_set_width(ui_HumidityText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HumidityText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityText, "Humidity •");
    lv_obj_set_style_text_font(ui_HumidityText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindText = lv_label_create(ui_WeatherConditionContainer);
    lv_obj_set_width(ui_WindText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WindText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindText, "Wind •");
    lv_obj_set_style_text_font(ui_WindText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityText = lv_label_create(ui_WeatherConditionContainer);
    lv_obj_set_width(ui_AirQualityText, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirQualityText, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AirQualityText, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualityText, "Air Quality •");
    lv_obj_set_style_text_font(ui_AirQualityText, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Percent1 = lv_label_create(ui_WeatherContainer);
    lv_obj_set_width(ui_Percent1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percent1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percent1, 48);
    lv_obj_set_y(ui_Percent1, 14);
    lv_obj_set_align(ui_Percent1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Percent1, "%");
    lv_obj_set_style_text_font(ui_Percent1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Percent2 = lv_label_create(ui_WeatherContainer);
    lv_obj_set_width(ui_Percent2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percent2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percent2, 48);
    lv_obj_set_y(ui_Percent2, -2);
    lv_obj_set_align(ui_Percent2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Percent2, "%");
    lv_obj_set_style_text_font(ui_Percent2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mph = lv_label_create(ui_WeatherContainer);
    lv_obj_set_width(ui_mph, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mph, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mph, 56);
    lv_obj_set_y(ui_mph, 29);
    lv_obj_set_align(ui_mph, LV_ALIGN_CENTER);
    lv_label_set_text(ui_mph, "mph");
    lv_obj_set_style_text_font(ui_mph, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherConditionValContainer = lv_obj_create(ui_WeatherContainer);
    lv_obj_remove_style_all(ui_WeatherConditionValContainer);
    lv_obj_set_width(ui_WeatherConditionValContainer, 21);
    lv_obj_set_height(ui_WeatherConditionValContainer, 60);
    lv_obj_set_x(ui_WeatherConditionValContainer, 30);
    lv_obj_set_y(ui_WeatherConditionValContainer, 23);
    lv_obj_set_align(ui_WeatherConditionValContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherConditionValContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherConditionValContainer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START,
                          LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_WeatherConditionValContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PrecipitationValue = lv_label_create(ui_WeatherConditionValContainer);
    lv_obj_set_width(ui_PrecipitationValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PrecipitationValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PrecipitationValue, -10);
    lv_obj_set_y(ui_PrecipitationValue, -25);
    lv_obj_set_align(ui_PrecipitationValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PrecipitationValue, "25");
    lv_obj_set_style_text_font(ui_PrecipitationValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HumidityValue = lv_label_create(ui_WeatherConditionValContainer);
    lv_obj_set_width(ui_HumidityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityValue, -11);
    lv_obj_set_y(ui_HumidityValue, -9);
    lv_obj_set_align(ui_HumidityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityValue, "25");
    lv_obj_set_style_text_font(ui_HumidityValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WindValue = lv_label_create(ui_WeatherConditionValContainer);
    lv_obj_set_width(ui_WindValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindValue, 2);
    lv_obj_set_y(ui_WindValue, -6);
    lv_obj_set_align(ui_WindValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindValue, "2");
    lv_obj_set_style_text_font(ui_WindValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AirQualityValue = lv_label_create(ui_WeatherConditionValContainer);
    lv_obj_set_width(ui_AirQualityValue, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AirQualityValue, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AirQualityValue, -11);
    lv_obj_set_y(ui_AirQualityValue, 22);
    lv_obj_set_align(ui_AirQualityValue, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AirQualityValue, "25");
    lv_obj_set_style_text_font(ui_AirQualityValue, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Celsius = lv_label_create(ui_HomeScreen);
    lv_obj_set_width(ui_Celsius, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Celsius, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Celsius, -41);
    lv_obj_set_y(ui_Celsius, -97);
    lv_obj_set_align(ui_Celsius, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Celsius, "° C");
    lv_obj_set_style_text_font(ui_Celsius, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateTimeContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_DateTimeContainer);
    lv_obj_set_width(ui_DateTimeContainer, 142);
    lv_obj_set_height(ui_DateTimeContainer, 73);
    lv_obj_set_x(ui_DateTimeContainer, 84);
    lv_obj_set_y(ui_DateTimeContainer, 69);
    lv_obj_set_align(ui_DateTimeContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DateTimeContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DateTimeContainer, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DateTimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DateTimeContainer, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DateTimeContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DateTimeContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DateTimeContainer, lv_color_hex(0xFCF9F9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DateTimeContainer, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DateTimeContainer, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeekContainer = lv_obj_create(ui_DateTimeContainer);
    lv_obj_remove_style_all(ui_WeekContainer);
    lv_obj_set_width(ui_WeekContainer, 126);
    lv_obj_set_height(ui_WeekContainer, 20);
    lv_obj_set_x(ui_WeekContainer, -5);
    lv_obj_set_y(ui_WeekContainer, 8);
    lv_obj_set_align(ui_WeekContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_WeekContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Day = lv_label_create(ui_WeekContainer);
    lv_obj_set_width(ui_Day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Day, "Saturday");
    lv_obj_set_style_text_color(ui_Day, lv_color_hex(0x0A192F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Day, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DateContainer = lv_obj_create(ui_DateTimeContainer);
    lv_obj_remove_style_all(ui_DateContainer);
    lv_obj_set_width(ui_DateContainer, 118);
    lv_obj_set_height(ui_DateContainer, 16);
    lv_obj_set_x(ui_DateContainer, 5);
    lv_obj_set_y(ui_DateContainer, -13);
    lv_obj_set_align(ui_DateContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DateContainer, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_DateContainer, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_DateContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Month = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_Month, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Month, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Month, -38);
    lv_obj_set_y(ui_Month, -16);
    lv_obj_set_align(ui_Month, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Month, "March");
    lv_obj_set_style_text_color(ui_Month, lv_color_hex(0x0A192F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Month, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, 14);
    lv_obj_set_y(ui_Date, -15);
    lv_obj_set_align(ui_Date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Date, "14,");
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0x0A192F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Year = lv_label_create(ui_DateContainer);
    lv_obj_set_width(ui_Year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Year, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Year, "2026");
    lv_obj_set_style_text_color(ui_Year, lv_color_hex(0x0A192F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Year, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PlaceContainer = lv_obj_create(ui_DateTimeContainer);
    lv_obj_remove_style_all(ui_PlaceContainer);
    lv_obj_set_width(ui_PlaceContainer, 145);
    lv_obj_set_height(ui_PlaceContainer, 18);
    lv_obj_set_align(ui_PlaceContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PlaceContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Location = lv_label_create(ui_PlaceContainer);
    lv_obj_set_width(ui_Location, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Location, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Location, -3);
    lv_obj_set_y(ui_Location, 3);
    lv_obj_set_align(ui_Location, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Location, "Phoenix, AZ");
    lv_obj_set_style_text_color(ui_Location, lv_color_hex(0x0A192F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Location, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MiscContainer = lv_obj_create(ui_HomeScreen);
    lv_obj_remove_style_all(ui_MiscContainer);
    lv_obj_set_width(ui_MiscContainer, 161);
    lv_obj_set_height(ui_MiscContainer, 79);
    lv_obj_set_x(ui_MiscContainer, -74);
    lv_obj_set_y(ui_MiscContainer, 50);
    lv_obj_set_align(ui_MiscContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MiscContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PokeContainer = lv_obj_create(ui_MiscContainer);
    lv_obj_remove_style_all(ui_PokeContainer);
    lv_obj_set_width(ui_PokeContainer, 158);
    lv_obj_set_height(ui_PokeContainer, 50);
    lv_obj_set_x(ui_PokeContainer, -1);
    lv_obj_set_y(ui_PokeContainer, -12);
    lv_obj_set_align(ui_PokeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PokeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Piplup = lv_img_create(ui_PokeContainer);
    lv_img_set_src(ui_Piplup, &ui_img_piplup_png);
    lv_obj_set_width(ui_Piplup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Piplup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Piplup, -54);
    lv_obj_set_y(ui_Piplup, -3);
    lv_obj_set_align(ui_Piplup, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Piplup, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Piplup, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_Piplup, 3);

    ui_Mudkip = lv_img_create(ui_PokeContainer);
    lv_img_set_src(ui_Mudkip, &ui_img_mudkip_png);
    lv_obj_set_width(ui_Mudkip, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mudkip, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mudkip, 49);
    lv_obj_set_y(ui_Mudkip, -12);
    lv_obj_set_align(ui_Mudkip, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Mudkip, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Mudkip, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Ground = lv_obj_create(ui_PokeContainer);
    lv_obj_set_width(ui_Ground, 146);
    lv_obj_set_height(ui_Ground, 8);
    lv_obj_set_x(ui_Ground, -1);
    lv_obj_set_y(ui_Ground, 18);
    lv_obj_set_align(ui_Ground, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Ground, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Ground, 300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Ground, lv_color_hex(0x1F15A2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Ground, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wingull = lv_img_create(ui_PokeContainer);
    lv_img_set_src(ui_Wingull, &ui_img_wingull_png);
    lv_obj_set_width(ui_Wingull, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wingull, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wingull, -4);
    lv_obj_set_y(ui_Wingull, -5);
    lv_obj_set_align(ui_Wingull, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Wingull, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Wingull, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExtraContainer = lv_obj_create(ui_MiscContainer);
    lv_obj_remove_style_all(ui_ExtraContainer);
    lv_obj_set_width(ui_ExtraContainer, 142);
    lv_obj_set_height(ui_ExtraContainer, 15);
    lv_obj_set_x(ui_ExtraContainer, 2);
    lv_obj_set_y(ui_ExtraContainer, 27);
    lv_obj_set_align(ui_ExtraContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ExtraContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ExtraLabel = lv_label_create(ui_ExtraContainer);
    lv_obj_set_width(ui_ExtraLabel, 143);
    lv_obj_set_height(ui_ExtraLabel, 16);
    lv_obj_set_x(ui_ExtraLabel, -3);
    lv_obj_set_y(ui_ExtraLabel, -1);
    lv_obj_set_align(ui_ExtraLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_ExtraLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_ExtraLabel, "There is no shame in being weak. The shame is in staying weak.\n");
    lv_obj_clear_flag(ui_ExtraLabel, LV_OBJ_FLAG_SCROLL_ELASTIC);      /// Flags
    lv_obj_set_scroll_dir(ui_ExtraLabel, LV_DIR_LEFT);
    lv_obj_set_style_text_font(ui_ExtraLabel, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_HomeScreen_screen_destroy(void)
{
    if(ui_HomeScreen) lv_obj_del(ui_HomeScreen);

    // NULL screen variables
    ui_HomeScreen = NULL;
    ui_Clock = NULL;
    ui_SecondHand = NULL;
    ui_HourHand = NULL;
    ui_MinuteHand = NULL;
    ui_WeatherContainer = NULL;
    ui_WeatherWidget = NULL;
    ui_Temperature = NULL;
    ui_Weather = NULL;
    ui_WeatherConditionContainer = NULL;
    ui_PrecipitationText = NULL;
    ui_HumidityText = NULL;
    ui_WindText = NULL;
    ui_AirQualityText = NULL;
    ui_Percent1 = NULL;
    ui_Percent2 = NULL;
    ui_mph = NULL;
    ui_WeatherConditionValContainer = NULL;
    ui_PrecipitationValue = NULL;
    ui_HumidityValue = NULL;
    ui_WindValue = NULL;
    ui_AirQualityValue = NULL;
    ui_Celsius = NULL;
    ui_DateTimeContainer = NULL;
    ui_WeekContainer = NULL;
    ui_Day = NULL;
    ui_DateContainer = NULL;
    ui_Month = NULL;
    ui_Date = NULL;
    ui_Year = NULL;
    ui_PlaceContainer = NULL;
    ui_Location = NULL;
    ui_MiscContainer = NULL;
    ui_PokeContainer = NULL;
    ui_Piplup = NULL;
    ui_Mudkip = NULL;
    ui_Ground = NULL;
    ui_Wingull = NULL;
    ui_ExtraContainer = NULL;
    ui_ExtraLabel = NULL;

}
