// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP_Clock

#include "../ui.h"

lv_obj_t * ui_WiFiScreen = NULL;
lv_obj_t * ui_WiFiConnect = NULL;
lv_obj_t * ui_Spinner2 = NULL;
lv_obj_t * ui_QRCodeContainer = NULL;
lv_obj_t * ui_WiFiSetup = NULL;
// event funtions

// build funtions

void ui_WiFiScreen_screen_init(void)
{
    ui_WiFiScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WiFiScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_WiFiScreen, &ui_img_713335961, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiConnect = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_WiFiConnect, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiConnect, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiConnect, -67);
    lv_obj_set_y(ui_WiFiConnect, -87);
    lv_obj_set_align(ui_WiFiConnect, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiConnect, "Connecting to WiFi.....");

    ui_Spinner2 = lv_spinner_create(ui_WiFiScreen, 1000, 90);
    lv_obj_set_width(ui_Spinner2, 36);
    lv_obj_set_height(ui_Spinner2, 37);
    lv_obj_set_x(ui_Spinner2, 43);
    lv_obj_set_y(ui_Spinner2, -89);
    lv_obj_set_align(ui_Spinner2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Spinner2, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_QRCodeContainer = lv_obj_create(ui_WiFiScreen);
    lv_obj_remove_style_all(ui_QRCodeContainer);
    lv_obj_set_width(ui_QRCodeContainer, 90);
    lv_obj_set_height(ui_QRCodeContainer, 90);
    lv_obj_set_x(ui_QRCodeContainer, -64);
    lv_obj_set_y(ui_QRCodeContainer, -21);
    lv_obj_set_align(ui_QRCodeContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QRCodeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WiFiSetup = lv_label_create(ui_WiFiScreen);
    lv_obj_set_width(ui_WiFiSetup, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WiFiSetup, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WiFiSetup, -59);
    lv_obj_set_y(ui_WiFiSetup, 47);
    lv_obj_set_align(ui_WiFiSetup, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WiFiSetup, "Could not connect. Setup WiFi");
    lv_obj_add_flag(ui_WiFiSetup, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_WiFiSetup, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_WiFiScreen_screen_destroy(void)
{
    if(ui_WiFiScreen) lv_obj_del(ui_WiFiScreen);

    // NULL screen variables
    ui_WiFiScreen = NULL;
    ui_WiFiConnect = NULL;
    ui_Spinner2 = NULL;
    ui_QRCodeContainer = NULL;
    ui_WiFiSetup = NULL;

}
