// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: ESP_Clock

#ifndef UI_WIFISCREEN_H
#define UI_WIFISCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WiFiScreen
extern void ui_WiFiScreen_screen_init(void);
extern void ui_WiFiScreen_screen_destroy(void);
extern lv_obj_t * ui_WiFiScreen;
extern lv_obj_t * ui_WiFiConnect;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_QRCodeContainer;
extern lv_obj_t * ui_WiFiSetup;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

